### ISSUE TITLE
Implement HTML parse mode

### ISSUE THREAD

**Issue by dayatfadila7** [prasaath6/telegram_bot_message_with_php_codeigniter#2]
how to Implement HTML parse mode, i try to change the code like this

```
public function sendmsg($msg)
    {
        $telegram = new Telegram($this->ci->config->item('bot_toke
n', 'telegram'));
        $chat_id = $this->ci->config->item('chat_id', 'telegram');
        $content = array('parse_mode' => 'HTML','chat_id' => $chat_id, 'text' => $msg);
        return $telegram->sendMessage($content);
    }

```
but nothing working, please update to parse mode  :)

I would like to use this feature on the Bot

**Comment by prasaath6** [comment]
hi @dayatfadila7 
thanks for your interest,
can you please explain what you want to achieve 
for example:
I have below HTML:
`<h1>hi hello</h1>`
this should be removed HTML tag and print as 
`hi hello`
or this text should be bold to apply HTML tags
<h1>hi hello</h1>
like this

**Comment by dayatfadila7** [comment]
yes, that's what I want
if you use html tags that can run like in a browser
like we type the h1 tag
later it becomes:
<h1> Heading one </h1>
or we create a link
can <a href="example.com"> example links </a>

sorry if my language is messy, thank you for the response

**Comment by prasaath6** [comment]
sorry, this feature can't be done..but we will try and achieve this soon..
Thanks for your interest
